name: watchman
description: Watches a set of files for changes
version: 0.0.1
#homepage: https://aphorica.com
#author: rickb <rickb@aphorica.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

executables:
  watchman:
  
dependencies:
  watcher: ^0.9.7+3
  
#  path: ^1.4.1

